### PR TITLE
Test merge to check branch rules and ownership transfer.

### PR DESCRIPTION
**Pull request by ConorTighe1995**
Just a small README update to make sure the rules are applied, If this seems ok I will close the ticket.

Ive used the same branch rules as Reactor and transferred ownership to the web-dev-team.

closes ospin-web-dev/REACTor#791

### CODE REVIEW

**Comment by ConorTighe1995** [comment]
This will not auto close the PR so ill manually close it if you guys are happy with what has been done.

**Comment by DanielSeehausen** [comment]
@ConorTighe1995 to reference cross project tickets, you can do the following:

closes ospin-web-dev/REACTor#791

**Comment by DanielSeehausen** [comment]
would you be able to `npx create-react-app` for this? maybe add the base libraries too (react semantic UI

**Comment by ConorTighe1995** [comment]
> @ConorTighe1995 to reference cross project tickets, you can do the following:
> 
> closes [ospin-web-dev/REACTor#791](https://github.com/ospin-web-dev/REACTor/issues/791)

great thanks.

**Pull request merged**
